### ISSUE TITLE
Problems using erlware_commons as dependency

### ISSUE THREAD

**Issue by edevil** [erlware/erlware_commons#100]
I just upgraded one of my packages, exrm 1.0-rc7 -> rc8, and with it came a new dependency, erlware_commons. However, I can't seem to fetch it:

```
$ mix deps.get
Running dependency resolution
==> erlware_commons
Error evaluating rebar config script ./rebar.config.script:16: evaluation failed with reason error:{badmatch,undefined} and stacktrace [{erl_eval,expr,3,[]}]
Any dependency defined in the script won't be available unless you add them to your Mix project
```

There seems to be nothing wrong with rebar3 on my system:
```
$ rebar3 version
rebar 3.0.0-beta-2 on Erlang/OTP 18 Erts 7.2.1
```

Any clues as to what may be wrong? Is this even a problem? I'm using Elixir 1.2.2.

**Comment by tsloughter** [comment]
Maybe update your rebar3 version. You probably want to open this issue with exrm though, I don't know what mix is doing and someone over there is more likely to be able to help.

**Comment by edevil** [comment]
FYI, I upgraded rebar3 and the problem remained. I'll take it up with the exrm author. Thanks!

**Comment by parubets** [comment]
same problem here.... elixir app + exrm

**Comment by robinkruyt** [comment]
Same problem here. Problem goes away if you replace your erlware_commons/rebar.config.script with the one from https://github.com/erlware/erlware_commons/commit/8a325c02912a20a877d861cc72021505c145daaa
But this does not seem like a solution to me.

**Comment by adambadawy** [comment]
First reply here detailed a fix that worked for me:
bitwalker/exrm#294

**Comment by edevil** [comment]
It seems the issue has been fixed by 8a325c02912a20a877d861cc72021505c145daaa, but a new version has not been released that incorporates this. Any ETA on this?

**Comment by mingchuno** [comment]
+1 for new release

**Comment by edevil** [comment]
It seems a new version has been released. Thanks.
