### ISSUE TITLE
Discrepancy between hex.pm vs. the COPYING file

### ISSUE THREAD

**Issue by obrok** [erlware/erlware_commons#110]
The COPYING file has something that looks like an MIT license inside of it. Meanwhile hex.pm metadata states that `erlware_commons` is licensed under the Apache license.

**Comment by paulo-ferraz-oliveira** [comment]
This is still the case. I don't mind PR'ing to fix if I understand what license is correct (MIT or Apache).

**Comment by ferd** [comment]
It contains both licenses, actually. It has apache modules (ec_cmd_log.hrl, ec_cnv.erl, and ec_cmd_log.erl) on top of being MIT in general. Ideally we'd have both licenses listed.
