### ISSUE TITLE
please tag next version (0.23.0 ?)

### ISSUE THREAD

**Issue by velimir** [erlware/erlware_commons#116]

**Comment by carlisom** [comment]
Looks like they bumped it to 1.0.0 internally recently.

https://github.com/erlware/erlware_commons/commit/c9f1c5debe2ee4ca7fa2afb8d143318c15fadfe7

**Comment by velimir0xff** [comment]
@tsloughter do you mind tagging it 1.0.0?

**Comment by velimir0xff** [comment]
@tsloughter @ericbmerritt @lrascao @jwilberding  package is bumped to 1.0 according to https://github.com/erlware/erlware_commons/commit/c9f1c5debe2ee4ca7fa2afb8d143318c15fadfe7 do you have any objections to tag repo with 1.0 tag?

**Comment by tsloughter** [comment]
Sure. I tend not to tag them anymore since I just publish to hex with the version and don't use git dependencies.

**Comment by velimir0xff** [comment]
thank you @tsloughter !

Tag created: https://github.com/erlware/erlware_commons/releases/tag/1.0.0

**Comment by velimir0xff** [comment]
@tsloughter I just realised you tagged not a HEAD of the master, but version from Jan 8. Is that possible to tag current master, please?

**Comment by tsloughter** [comment]
That is 1.0.0, current master hasn't been published yet.

**Comment by carlisom** [comment]
1.0.0 is broken for project that have not moved to rebar3 yet on and run on erlang 19.1, any ETA for the new release that will fix this issues?

**Comment by carlisom** [comment]
@tsloughter please see above comment

**Comment by tsloughter** [comment]
What do you mean? Is there a patch that fixes the issue you have?

**Comment by velimir0xff** [comment]
@tsloughter I think this one https://github.com/erlware/erlware_commons/pull/107 it's been merged already

**Comment by paulo-ferraz-oliveira** [comment]
4 years in, I don't think tagged/published versions are an issue any more 😄

**Comment by velimir** [comment]
Don't work for the project any longer. @carlisom do you still need this tagged? I already forgot why we needed this :)

**Comment by ferd** [comment]
yeah we've kept versioning things, just differently. I'll close this, I don't think this is really relevant anymore.
