### ISSUE TITLE
ec_file:copy fails for not owned source file with OTP 21-rc2

### ISSUE THREAD

**Issue by shino** [erlware/erlware_commons#133]
- commit b23bf733c5d949e746f7560664b6855eb85eed93
- erlang/OTP : 21-rc2

For the file owned by root user, ec_file:coy fails if executed by non-root user.

Steps to reproduce:

```
(default) % rm -f a && sudo touch a && sudo chmod 755 a
(default) % ls -al a
-rwxr-xr-x  1 root  staff  0 Jun  7 14:07 a
(default) % ./rebar3 shell
===> Verifying dependencies...
===> Compiling erlware_commons
Erlang/OTP 21 [RELEASE CANDIDATE 2] [erts-10.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:0] [hipe] [sharing-preserving]

Eshell V10.0  (abort with ^G)
1> ec_file:copy("a", "b").
{error,{write_file_info_failed,eperm}}
```

This does not fail with OTP 20.3.4.

----

From the doc of 21-rc2, file_info record has been added some fields.

- http://erlang.org/documentation/doc-10.0-rc2/lib/kernel-6.0/doc/html/file.html#type-file_info
- http://erlang.org/doc/man/file.html#type-file_info

Therefore, this is caused by  (potential) incompatibility of Erlang/OTP.
If you decide this is not a bug of erlware_commons, please just close ;)

**Comment by shino** [comment]
> From the doc of 21-rc2, file_info record has been added some fields.

I'm sorry, the file_info record has not been changed;

**Comment by shino** [comment]
FWIW: Difference comes from treatment of eperm on chown.

[erlang-questions] Maybe potential incompatibility of file_info record
http://erlang.org/pipermail/erlang-questions/2018-June/095612.html

**Comment by shino** [comment]
Decision for OTP 21 has been settled:

> This is an intentional bugfix, and I've added a release note for it
> now. Thanks for reporting it!

[erlang-questions] Maybe potential incompatibility of file_info record
http://erlang.org/pipermail/erlang-questions/2018-June/095645.html

Therefore, write_file_info can fail by `eperm` after OTP 21.

**Comment by kubantsev** [comment]
It fails on OTP 21
```
    From = "/usr/bin/test",
    To = "/tmp/test.test.test",
    file:delete(To),
    file:copy(From, To),
    {ok, FI} = file:read_file_info(From),
    file:write_file_info(To, FI).
{error,eperm}
```

**Comment by tsloughter** [comment]
Yea, this is a change/fix in OTP-21. Not sure what the best solution is yet.

**Comment by shino** [comment]
I don't have nice way to fix the bug yet...
For discussion purpose, here is one of the ways to fix:

1. Try `file:write_file_info` with full SrcFileInfo as it is now. 
2. if 1. succeeds, it's ok.
3. if 1. fails, try `file:write_file_info(Path, SrcFileInfo#file_info{uid=undefined, gid=undefined}` .

Pros:
- It works as is for OTP 20-
- For OTP 21+, it's almost the same behavior as OTP 20-
  - in case it's executed by root user, it changes owner/group to source's one
  - in case it's executed by non-root user, it does *not* fail without changing ower/group

Cons:
- It can be slower (because try two times)

**Comment by tsloughter** [comment]
@shino I have a PR you can look at, it works similarly to that.

**Comment by shino** [comment]
It has fine grained control from outside, so it look nice.
Thanks for the PR!

**Comment by shino** [comment]
Rebar3 was released. Close this.

Thanks for fixing!
