### ISSUE TITLE
runmany_wrap doesn't actually call the passed function

### ISSUE THREAD

**Issue by markan** [erlware/erlware_commons#138]
I noticed that runmany_wrap doesn't actually call the function passed to it, it only returns it. Looks like some parens were dropped during the refactor (see https://github.com/erlware/erlware_commons/blob/master/src/ec_plists.erl#L878) 

I think that's slipped through testing because the ec_plist map tests only test the default malt, which uses the local runmany local code path. 

This seems straightforward, so I wrote a quick fix here: https://github.com/chef/erlware_commons/tree/ma/fix_for_ftmap. Happy to make it a PR if you like.

**Comment by ariel-anieli** [comment]
Fixed by https://github.com/erlware/erlware_commons/pull/163.
