### ISSUE TITLE
Warnings emitted on OTP 24 prevent Rebar 3 bootstrap

### ISSUE THREAD

**Issue by michaelklishin** [erlware/erlware_commons#145]
This project is a dependency of Rebar 3. It has recently started failing bootstrap on Erlang/OTP 24 (master) due to the following warning:

```
/path/to/rebar3-src/_build/default/lib/erlware_commons/src/ec_cmd_log.erl:160: Warning: ambiguous call of overridden auto-imported BIF error/3
 - use erlang:error/3 or "-compile({no_auto_import,[error/3]})." to resolve name clash
```

Most likely this warning is relatively new but I did not spend any time trying to trace it to a specific OTP commit.

**Comment by ferd** [comment]
yeah, they merged the EEP-54 stuff which means a bunch of our calls may start exploding now... will need to rewrite stuff in dependencies and that's gonna be a whole ordeal. This happens from major release to major release, but we'll have to find time and audit all the deps and patch them all up.
