### ISSUE TITLE
Request for Hex.pm publication

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [erlware/erlware_commons#153]
I'd like to ask this (`master`?) to be published to Hex.pm, in order for it to be imported into `rebar3` as per one of the actions identified in https://github.com/erlang/rebar3/pull/2515. Thanks.

---

**Edit**: `master` handles, among other stuff, https://github.com/erlang/rebar3/pull/2515#issuecomment-800355884.

**Comment by ferd** [comment]
Yeah worth doing. Currently only @tsloughter has publishing rights to erlware_commons on hex. I can cut releases here, but can't publish over there.

**Comment by paulo-ferraz-oliveira** [comment]
Thanks, @ferd. No hurry, though, at least until we want to close the linked `rebar3` issue.

**Comment by paulo-ferraz-oliveira** [comment]
@tsloughter, if you have time would you think this possible (Hex.pm publication)? (or probably share the burden with @ferd if he's up for it 😄). Thanks. I'd like to import this to `rebar3` soonish, since 24 is "around the corner" I imagine (heard half-May somewhere).

**Comment by tsloughter** [comment]
Sorry about that, 1.6.0 has been published.
