### ISSUE TITLE
ec_file:copy(Source, Dest, [recursive]) not respecting symlinks

### ISSUE THREAD

**Issue by davidw** [erlware/erlware_commons#69]
To see this in action?

```
mkdir a
touch a/x
cd a
ln -s x y
```

From Erlang:

```
ec_file:copy("a", "b", [recursive]).
```

Doing an ls -lah shows that the symlinks have not been preserved.

Is it supposed to do this?  It does not seem right to me.

**Comment by tsloughter** [comment]
Hm, will look into this.
