### ISSUE TITLE
ec_plists:map can be affected by any DOWN message

### ISSUE THREAD

**Issue by budzejko** [erlware/erlware_commons#87]
The receivefrom function (https://github.com/erlware/erlware_commons/blob/master/src/ec_plists.erl#L771) matches all DOWN messages, not only from spawned processes (BadPid instead of Pid).
```
receivefrom(Pid) ->
    receive
        {Pid, R} ->
            R;
        {'DOWN', _, _, BadPid, Reason} when Reason =/= normal ->
            erlang:throw({BadPid, Reason});
        {timerrang, _} ->
            erlang:throw({nil, timeout})
    end.
```
This results e.g. ec_plists:map failure when DOWN from other sources is in message queue.

Ref from {Pid, _} = erlang:spawn_monitor(F), is also ignored (https://github.com/erlware/erlware_commons/blob/master/src/ec_plists.erl#L755).

**Comment by ericbmerritt** [comment]
Thanks @budzejko thats a nice catch.

**Comment by tsloughter** [comment]
@budzejko want to send a PR to fix this up? Thanks!

**Comment by budzejko** [comment]
Sure :)

**Comment by budzejko** [comment]
PR #97
