### ISSUE TITLE
compiling is broken

### ISSUE THREAD

**Issue by Sepuka** [erlware/erlware_commons#95]
It seems that last commit broke project compiling. 

```
.../portal/rebar compile
WARN:  Expected .../portal/deps/cf to be an app dir (containing ebin/*.app), but no .app found.
==> erlware_commons (compile)
WARN:  Expected .../portal/deps/cf to be an app dir (containing ebin/*.app), but no .app found.
Dependency not available: cf-.* (undefined)
ERROR: compile failed while processing .../portal/deps/erlware_commons: rebar_abort
make: *** [compile-full]
```

**Comment by tsloughter** [comment]
Yes, this is a continuation of the move to rebar3. Best would be for you to either upgrade to rebar3 or add `cf` as a dep to your toplevel so that rebar2 fetches it itself and erlware_commons won't complain (I believe).

**Comment by Sepuka** [comment]
ok, thank you
i just added
```
{cf, ".*", {git, "https://github.com/project-fifo/cf.git"}}
```
deps to rebar and i see that
```
cd rel && .../portal/rebar generate -f overlay_vars=vars/vars.default.config target_dir=...
==> rel (generate)
{"init terminating in do_boot",{{badmatch,false},[{reltool_target,do_merge_apps,5,[{file,"reltool_target.erl"},{line,345}]},{reltool_target,merge_apps,2,[{file,"reltool_target.erl"},{line,335}]},{reltool_target,do_spec_rel_files,2,[{file,"reltool_target.erl"},{line,769}]},{reltool_target,'-spec_rel_files/1-lc$^0/1-0-',2,[{file,"reltool_target.erl"},{line,763}]},{reltool_target,spec_rel_files,1,[{file,"reltool_target.erl"},{line,763}]},{reltool_target,do_gen_spec,1,[{file,"reltool_target.erl"},{line,826}]},{reltool_target,gen_spec,1,[{file,"reltool_target.erl"},{line,814}]},{reltool_server,loop,1,[{file,"reltool_server.erl"},{line,396}]}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
make[1]: *** [generate-new]
```
propably, need use rebar3 only?

**Comment by tsloughter** [comment]
Seems to be something wrong with the reltool config, can't help there. You can just pin your `erlware_commons` dep to `0.15.0` instead of using the latest. Nothing really but color output stuff has changed.

**Comment by Sepuka** [comment]
maybe rebar2 dont understand atom style deps? and app merge failed
p.s. when i use rebar3 i got error
```
undefined parse transform 'merl_transform'
```
but this another history...

**Comment by tsloughter** [comment]
Right, rebar2 can't use a dep that is defined like `{deps, [cf]}.`, so until you use rebar3 simply stick with erlware_commons 0.15.0.

**Comment by paulo-ferraz-oliveira** [comment]
I'm not sure this is a real issue any more.

**Comment by ferd** [comment]
The issue is still valid (we broke rebar 2 compat), but it's never gonna be fixed.
